version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: django-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    environment:
      - VITE_API_URL=${API_URL}
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
